### ISSUE TITLE
Git Pager 替换 Markdown 输入框为 HTML 编辑器

### ISSUE THREAD

**Issue by TechQuery** [kaiyuanshe/OSS-toolbox#12]
## Is there an existing feature request for this?

- [X] I have searched the existing feature requests

## Description

原有的 Markdown 输入框基于 Markdown 输入法库实现，该库有 bug、久未更新，且依赖纯 Markdown 语法输入、编辑对大多数国人（包括码农）都要求较高，因此欲更换为有工具类按钮的 HTML 编辑器。

### 推荐库

https://github.com/idea2app/Edkit/tree/master/React/

### 参考代码

https://github.com/kaiyuanshe/OpenHackathon-Web/blob/4a80163f1d3ee8e11cac5083a0c62e0f78580465/components/Activity/ActivityEditor.tsx#L275-L278

### 目标位置

https://github.com/kaiyuanshe/OSS-toolbox/blob/4d057a6b56508f5a6bfa7be3ab6bdcdc3d6f0e1c/components/Git/ArticleEditor.tsx#L316

**Comment by luojiyin1987** [comment]
- [ ] 实现 UI 优化，交互的友好性提高
- [x] 编辑器替换 @luojiyin1987
