### ISSUE TITLE
底部上拉没有数据时仍显示“加载更多......”

### ISSUE THREAD

**Issue by hu-qi** [kaiyuanshe/OSS-toolbox#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/kaiyuanshe/OSS-toolbox/assets/17986122/4db4a353-f2f0-47f5-a01c-f0901c42e64b)

### Expected Behavior

![image](https://github.com/kaiyuanshe/OSS-toolbox/assets/17986122/5262a6b7-556c-47e1-93c8-58899b94b63a)

### Steps To Reproduce

1. 访问 https://oss-toolbox.kaiyuanshe.cn/
2. 一直往上拉，在 page = 7 的时候就已经没有数据了

```
https://oss-toolbox.kaiyuanshe.cn/api/GitHub/orgs/kaiyuanshe/repos?type=public&sort=pushed&page=7&per_page=10

response：
[]

```

### What kind of hardware did the bug occur on?

Desktop, Pad, Phone

### On which operating system are you experiencing the problem?

Windows, MacOS, Android

### The version of your Operation System

Windows 11 专业版 23H2; macOS Ventura 13.6.7;Xiaomi HyperOS 1.0.3.0 UMRCNXM

### What browsers are you seeing the problem on?

Chrome, Arc Browser

### The version of your Web browser

Google Chrome 124.0.6367.119

### What kind of network are you connecting to?

WLAN, WiFi, 4G, 5G

### What network region are you in?

China mainland

**Comment by hu-qi** [comment]
尝试修复但遇到困难，定位到上拉加载更多由 [mobx-restful-table](https://github.com/idea2app/MobX-RESTful-table/blob/d9a13ee635dd8c60e1c465bd33c1c7662159650b/source/ScrollList.tsx#L52) 实现，我想在 [models/Repository.ts](https://github.com/kaiyuanshe/OSS-toolbox/blob/ab4806291e6bdb682b0722a34e5b7271fa1f0965/models/Repository.ts#L89) 这个位置判断 list.length 为 0 时去修改 noMore 为 True ，但不知道如何编写代码。

- mobx-restful-table loadMore ：
```ts
 loadMore = debounce((edge: EdgePosition) => {
    const { store } = this.props;

    if (edge === 'bottom' && store.downloading < 1 && !store.noMore)
      store.getList();
  });
```

- 业务：

```ts
 async loadPage(
    page: number,
    per_page: number,
    { relation }: RepositoryFilter,
  ) {
    const { body: list } = await this.client.get<Repository[]>(
      `${this.baseURI}?${buildURLData({
        type: 'public',
        sort: 'pushed',
        page,
        per_page,
      })}`,
    );

   //  尝试在此处修改 noMore ，但不知道如何实现

    const pageData = await Promise.all(
      list!.map(async item => ({
        ...item,
        ...(await this.getOneRelation(item.full_name, relation)),
      })),
    );
    const [_, organization] = this.baseURI.split('/');

    const { body } = await this.client.get<Organization>(
      `orgs/${organization}`,
    );
    return { pageData, totalCount: body!.public_repos };
  }
}
```

**Comment by hu-qi** [comment]
> 尝试修复但遇到困难，定位到上拉加载更多由 [mobx-restful-table](https://github.com/idea2app/MobX-RESTful-table/blob/d9a13ee635dd8c60e1c465bd33c1c7662159650b/source/ScrollList.tsx#L52) 实现，我想在 [models/Repository.ts](https://github.com/kaiyuanshe/OSS-toolbox/blob/ab4806291e6bdb682b0722a34e5b7271fa1f0965/models/Repository.ts#L89) 这个位置判断 list.length 为 0 时去修改 noMore 为 True ，但不知道如何编写代码。
> 
> * mobx-restful-table loadMore ：
> 
> ```ts
>  loadMore = debounce((edge: EdgePosition) => {
>     const { store } = this.props;
> 
>     if (edge === 'bottom' && store.downloading < 1 && !store.noMore)
>       store.getList();
>   });
> ```
> 
> * 业务：
> 
> ```ts
>  async loadPage(
>     page: number,
>     per_page: number,
>     { relation }: RepositoryFilter,
>   ) {
>     const { body: list } = await this.client.get<Repository[]>(
>       `${this.baseURI}?${buildURLData({
>         type: 'public',
>         sort: 'pushed',
>         page,
>         per_page,
>       })}`,
>     );
> 
>    //  尝试在此处修改 noMore ，但不知道如何实现
> 
>     const pageData = await Promise.all(
>       list!.map(async item => ({
>         ...item,
>         ...(await this.getOneRelation(item.full_name, relation)),
>       })),
>     );
>     const [_, organization] = this.baseURI.split('/');
> 
>     const { body } = await this.client.get<Organization>(
>       `orgs/${organization}`,
>     );
>     return { pageData, totalCount: body!.public_repos };
>   }
> }
> ```
好像改好了，似懂非懂

**Comment by TechQuery** [comment]
排查到原因了：

1. `<ScrollList />` 初始化服务端渲染的数据时无法得知 `totalCount`：https://github.com/idea2app/MobX-RESTful-table/blob/d9a13ee635dd8c60e1c465bd33c1c7662159650b/source/ScrollList.tsx#L40

2. `ListModel.prototype.restoreList()` 的 `totalCount` 默认值是 `Infinity`，即有初始数据时须有总数（未知时为无限）：https://github.com/idea2app/MobX-RESTful/blob/d633176aca52269d5c1e6297ba8913c252eefb40/source/List.ts#L97-L101

3. `ListModel.prototype.loadPage()` 没能更新现有总数，以致永远无法大于 `Infinity`：https://github.com/idea2app/MobX-RESTful/blob/d633176aca52269d5c1e6297ba8913c252eefb40/source/List.ts#L149

我会在本月 TS 5.5 发布后合并 idea2app/MobX-RESTful#15，但因 Next.js 无法在 Node.js 正式支持 `require('es-modules')` 前支持新版依赖库，如需修正本项目，须复制以下代码到 `RepositoryModel` 子类来覆盖旧版本父类同名方法：https://github.com/idea2app/MobX-RESTful/blob/0ab190d11a6871da838f1734aa75128554152c35/source/List.ts#L135-L155
